// ============================================================================
// BEAT-SPECIFIC TERMINAL CONTENT
// Educational terminal output that mirrors sidebar "How It Works" content
// ============================================================================

/**
 * Maps story beat IDs to custom terminal output arrays.
 * Each beat gets content that directly demonstrates what's being taught.
 */
export const BEAT_TERMINAL_CONTENT: Record<string, string[]> = {
  // ==========================================================================
  // CHAPTER 1: THE ARCANE LOOP (Agent Architecture)
  // ==========================================================================

  'what-is-agentic': [
    '$ claude "add input validation to login form"',
    '',
    '> Starting agentic loop...',
    '> Analyzing codebase structure...',
    '',
    '╭─ Loop 1 ─────────────────────────────────────╮',
    '│ Read: src/components/LoginForm.tsx          │',
    '│ Status: Understanding current implementation │',
    '╰──────────────────────────────────────────────╯',
    '',
    '╭─ Loop 2 ─────────────────────────────────────╮',
    '│ Edit: src/components/LoginForm.tsx          │',
    '│ Status: Adding email regex validation       │',
    '╰──────────────────────────────────────────────╯',
    '',
    '╭─ Loop 3 ─────────────────────────────────────╮',
    '│ Bash: npm test -- LoginForm                 │',
    '│ Status: Verifying changes work              │',
    '╰──────────────────────────────────────────────╯',
    '',
    '╭─ Loop 4 ─────────────────────────────────────╮',
    '│ Edit: src/components/LoginForm.tsx          │',
    '│ Status: Fixing test failure                 │',
    '╰──────────────────────────────────────────────╯',
    '',
    '> Loop complete. Task finished in 4 iterations.',
  ],

  'the-loop': [
    '> The Agentic Loop - Each Iteration',
    '',
    '┌─────────────────────────────────────────────┐',
    '│ Step 1: Build message array                 │',
    '│   system_prompt + conversation + new_prompt │',
    '├─────────────────────────────────────────────┤',
    '│ Step 2: API call to Claude                  │',
    '│   response = claude(messages, tools)        │',
    '├─────────────────────────────────────────────┤',
    '│ Step 3: Check stop reason                   │',
    '│   if stop_reason == "end_turn":             │',
    '│     → Return response to user               │',
    '├─────────────────────────────────────────────┤',
    '│ Step 4: Execute tool calls                  │',
    '│   for tool in response.tool_calls:          │',
    '│     result = execute(tool)                  │',
    '├─────────────────────────────────────────────┤',
    '│ Step 5: Append results, loop back           │',
    '│   messages.append(tool_results)             │',
    '│   → Go to Step 1                            │',
    '└─────────────────────────────────────────────┘',
  ],

  'model-is-80': [
    '$ claude "refactor auth system"',
    '',
    '> Model reasoning (internal):',
    '  "I need to understand the current auth flow,',
    '   identify pain points, and propose changes.',
    '   Let me start by reading the auth files..."',
    '',
    '> Tool calls decided by model:',
    '  1. Grep: "authentication" in src/',
    '  2. Read: src/auth/index.ts',
    '  3. Read: src/middleware/auth.ts',
    '',
    '> Model decision: "The auth middleware has',
    '  duplicate validation logic. I\'ll consolidate."',
    '',
    '> Edit: src/auth/index.ts',
    '> Edit: src/middleware/auth.ts',
    '',
    '───────────────────────────────────────────────',
    'The MODEL decides the approach.',
    'Your job: Good prompts + good CLAUDE.md',
  ],

  'model-selection': [
    '> Model Selection Guide',
    '',
    '┌─ Sonnet (Default) ───────────────────────────┐',
    '│ Speed: ████████████ Fast                     │',
    '│ Cost:  ██░░░░░░░░░░ ~$3/1M tokens            │',
    '│ Best for:                                    │',
    '│   • Clear, well-defined tasks               │',
    '│   • Boilerplate and refactoring             │',
    '│   • Implementation after planning           │',
    '└──────────────────────────────────────────────┘',
    '',
    '┌─ Opus ───────────────────────────────────────┐',
    '│ Speed: ████░░░░░░░░ Deliberate               │',
    '│ Cost:  ████████████ ~$15/1M tokens           │',
    '│ Best for:                                    │',
    '│   • Complex architecture decisions          │',
    '│   • Subtle bugs requiring deep reasoning    │',
    '│   • Novel problems without clear path       │',
    '└──────────────────────────────────────────────┘',
    '',
    '$ /model opus      # Switch to Opus',
    '$ /model sonnet    # Switch back to Sonnet',
    '$ Shift+Tab+Tab    # Plan mode (uses Opus)',
  ],

  // ==========================================================================
  // CHAPTER 2: THE ARCANE RESERVOIR (Context)
  // ==========================================================================

  'what-claude-sees': [
    '> What Claude Receives Per API Call',
    '',
    '┌─ System Prompt ──────────────────────────────┐',
    '│ CLAUDE.md content           ~2,500 tokens   │',
    '│ Tool definitions (8 tools)  ~1,200 tokens   │',
    '│ Active skills               ~500 tokens     │',
    '│ Base instructions           ~800 tokens     │',
    '├──────────────────────────────────────────────┤',
    '│ Subtotal:                   ~5,000 tokens   │',
    '└──────────────────────────────────────────────┘',
    '',
    '┌─ Conversation History ───────────────────────┐',
    '│ User messages                               │',
    '│ Assistant responses                         │',
    '│ Tool call requests                          │',
    '│ Tool results (file contents, etc.)          │',
    '├──────────────────────────────────────────────┤',
    '│ Current conversation:       ~28,000 tokens  │',
    '└──────────────────────────────────────────────┘',
    '',
    '┌─ Your New Message ───────────────────────────┐',
    '│ "fix the bug in checkout"   ~8 tokens       │',
    '└──────────────────────────────────────────────┘',
    '',
    'Total this turn: ~33,008 tokens',
    'Context window: 200,000 tokens available',
  ],

  'context-degrades': [
    '> Context Window Quality Zones',
    '',
    '  0%                                      100%',
    '  │░░░░░░░░░░│░░░░░░░░░░│▓▓▓▓▓▓▓▓▓│████████│',
    '       ↓           ↓          ↓         ↓',
    '    Optimal    Good      Warning    Danger',
    '',
    '┌─ 0-20% (~40K tokens) ────────────────────────┐',
    '│ ● Full attention on all context             │',
    '│ ● Best quality responses                    │',
    '│ ● Recommended operating range               │',
    '└──────────────────────────────────────────────┘',
    '',
    '┌─ 20-35% ─────────────────────────────────────┐',
    '│ ● Slight degradation begins                 │',
    '│ ● Earlier messages may lose priority        │',
    '└──────────────────────────────────────────────┘',
    '',
    '┌─ 35-50% ─────────────────────────────────────┐',
    '│ ▲ WARNING: Significant degradation          │',
    '│ ● May miss details from earlier context     │',
    '│ ● Consider using /compact                   │',
    '└──────────────────────────────────────────────┘',
    '',
    '┌─ 50%+ ───────────────────────────────────────┐',
    '│ ✗ DANGER: High risk of errors               │',
    '│ ● Use /clear for fresh start                │',
    '└──────────────────────────────────────────────┘',
  ],

  'claudemd-memory': [
    '$ cat CLAUDE.md',
    '',
    '# Project: E-Commerce Platform',
    '',
    '## Build Commands',
    '- Build: npm run build',
    '- Test: npm test',
    '- Lint: npm run lint',
    '- Deploy: npm run deploy:staging',
    '',
    '## Architecture',
    '/src',
    '  /components  - React components',
    '  /hooks       - Custom hooks',
    '  /services    - API services',
    '  /utils       - Helper functions',
    '/server',
    '  /routes      - Express routes',
    '  /middleware  - Auth, logging',
    '  /models      - Prisma models',
    '',
    '## Conventions',
    '- Use TypeScript strict mode',
    '- Prefer composition over inheritance',
    '- All components must have tests',
    '- Use React Query for server state',
    '',
    '## Known Issues',
    '- Payment webhook timeout: Use 30s limit',
    '- Safari SVG bug: Use PNG fallback',
    '',
    '───────────────────────────────────────────────',
    'Settings hierarchy:',
    '  ~/.claude/CLAUDE.md      (user-level)',
    '  ./CLAUDE.md              (project root)',
    '  ./subdir/CLAUDE.md       (scoped)',
  ],

  'clear-and-compact': [
    '> Context Management Commands',
    '',
    '┌─ /clear ─────────────────────────────────────┐',
    '│ Wipes conversation history completely       │',
    '│ KEEPS: CLAUDE.md loaded                     │',
    '│ Cost: Free                                  │',
    '│                                             │',
    '│ $ /clear                                    │',
    '│ > Conversation cleared.                     │',
    '│ > CLAUDE.md still loaded.                   │',
    '│ > Ready for new task.                       │',
    '└──────────────────────────────────────────────┘',
    '',
    '┌─ /compact ───────────────────────────────────┐',
    '│ AI-summarizes conversation history          │',
    '│ PRESERVES: Key decisions & file changes     │',
    '│ Cost: ~2,000 tokens for summarization       │',
    '│                                             │',
    '│ $ /compact                                  │',
    '│ > Analyzing 156,231 tokens of history...    │',
    '│ > Creating intelligent summary...           │',
    '│                                             │',
    '│ Before:  156,231 tokens                     │',
    '│ After:    23,450 tokens                     │',
    '│ Saved:   132,781 tokens (85%)               │',
    '│                                             │',
    '│ Summary preserved:                          │',
    '│ - Auth system refactoring decisions         │',
    '│ - Files modified (12)                       │',
    '│ - Error resolutions (3)                     │',
    '└──────────────────────────────────────────────┘',
  ],

  // ==========================================================================
  // CHAPTER 3: ENCHANTED ARTIFACTS (Tools)
  // ==========================================================================

  'tools-overview': [
    '> The 8 Core Tools',
    '',
    '┌──────────┬────────────────────────────────────┐',
    '│ READ     │ Load file contents into context    │',
    '│          │ Supports: code, images, PDFs       │',
    '├──────────┼────────────────────────────────────┤',
    '│ EDIT     │ Surgical text replacement          │',
    '│          │ old_string → new_string            │',
    '├──────────┼────────────────────────────────────┤',
    '│ WRITE    │ Create new files or overwrite      │',
    '│          │ Use for new files only             │',
    '├──────────┼────────────────────────────────────┤',
    '│ BASH     │ Execute shell commands             │',
    '│          │ git, npm, docker, etc.             │',
    '├──────────┼────────────────────────────────────┤',
    '│ GREP     │ Search file contents (ripgrep)     │',
    '│          │ Regex, file types, context         │',
    '├──────────┼────────────────────────────────────┤',
    '│ GLOB     │ Find files by pattern              │',
    '│          │ **/*.tsx, src/**/test.*            │',
    '├──────────┼────────────────────────────────────┤',
    '│ TASK     │ Spawn subagents                    │',
    '│          │ Fresh context, returns summary     │',
    '├──────────┼────────────────────────────────────┤',
    '│ TODO     │ Track task progress                │',
    '│          │ Visible to user in UI              │',
    '└──────────┴────────────────────────────────────┘',
    '',
    'Each tool call adds to context.',
    'Claude decides which tools based on your prompt.',
  ],

  'read-tool': [
    '> Using Read tool...',
    '',
    '┌─ Source Code ────────────────────────────────┐',
    '│ $ Read: src/auth/login.ts                   │',
    '│                                             │',
    '│   1│ import { useState } from \'react\'       │',
    '│   2│ import { validateEmail } from \'./util\' │',
    '│   3│                                        │',
    '│   4│ export function LoginForm() {          │',
    '│   5│   const [email, setEmail] = useState(\'\')│',
    '│  ...                                        │',
    '│  47│ }                                      │',
    '│                                             │',
    '│ Added 47 lines to context                   │',
    '└──────────────────────────────────────────────┘',
    '',
    '┌─ Image File ─────────────────────────────────┐',
    '│ $ Read: docs/architecture.png               │',
    '│                                             │',
    '│ [Image analyzed visually by Claude]         │',
    '│ Detected: System architecture diagram       │',
    '│ Components: Auth service, API gateway...    │',
    '└──────────────────────────────────────────────┘',
    '',
    '┌─ PDF Document ───────────────────────────────┐',
    '│ $ Read: docs/api-spec.pdf                   │',
    '│                                             │',
    '│ Extracted 12 pages of text + tables         │',
    '│ API endpoints documented: 47                │',
    '└──────────────────────────────────────────────┘',
    '',
    'Tip: Use offset/limit for large files',
    '$ Read: large.ts (offset: 100, limit: 50)',
  ],

  'edit-write-tools': [
    '> Edit vs Write Tools',
    '',
    '┌─ EDIT: Surgical Replacement ─────────────────┐',
    '│ Must read file first!                       │',
    '│                                             │',
    '│ $ Edit: src/config.ts                       │',
    '│   old: "const timeout = 30"                 │',
    '│   new: "const timeout = 60"                 │',
    '│                                             │',
    '│ ✓ Applied change at line 42                 │',
    '│                                             │',
    '│ Note: old_string must be UNIQUE in file     │',
    '│ Include surrounding context if needed       │',
    '└──────────────────────────────────────────────┘',
    '',
    '┌─ WRITE: Create or Overwrite ─────────────────┐',
    '│ Creates new files                           │',
    '│                                             │',
    '│ $ Write: src/hooks/useAuth.ts               │',
    '│   content: [new hook implementation]        │',
    '│                                             │',
    '│ ✓ Created new file (48 lines)               │',
    '│                                             │',
    '│ Warning: Overwrites existing files!         │',
    '│ Use Edit for modifications                  │',
    '└──────────────────────────────────────────────┘',
    '',
    '$ Read → understand → Edit (preferred)',
    '$ Write (only for new files)',
  ],

  'bash-tool': [
    '> Using Bash tool...',
    '',
    '┌─ Git Operations ─────────────────────────────┐',
    '│ $ Bash: git status                          │',
    '│                                             │',
    '│ On branch feature/auth                      │',
    '│ Changes not staged:                         │',
    '│   modified: src/auth/login.ts               │',
    '│   modified: src/hooks/useAuth.ts            │',
    '│                                             │',
    '│ $ Bash: git add . && git commit -m "feat"   │',
    '│ ✓ [feature/auth abc123] feat: add auth      │',
    '└──────────────────────────────────────────────┘',
    '',
    '┌─ Package Management ─────────────────────────┐',
    '│ $ Bash: npm test -- --coverage              │',
    '│                                             │',
    '│ PASS src/auth/login.test.ts                 │',
    '│ PASS src/hooks/useAuth.test.ts              │',
    '│ Coverage: 94.2%                             │',
    '└──────────────────────────────────────────────┘',
    '',
    '┌─ What NOT to use Bash for ───────────────────┐',
    '│ ✗ cat file.ts    → Use Read tool            │',
    '│ ✗ echo > file    → Use Write tool           │',
    '│ ✗ sed/awk        → Use Edit tool            │',
    '└──────────────────────────────────────────────┘',
  ],

  'search-tools': [
    '> Search Tools: Grep & Glob',
    '',
    '┌─ GREP: Search Content ───────────────────────┐',
    '│ Pattern: "AuthContext"                      │',
    '│ Type: tsx                                   │',
    '│                                             │',
    '│ src/contexts/AuthContext.tsx                │',
    '│   12: export const AuthContext = createC... │',
    '│   45: <AuthContext.Provider value={...}>    │',
    '│                                             │',
    '│ src/hooks/useAuth.ts                        │',
    '│   3: import { AuthContext } from \'../cont...│',
    '│   8: const ctx = useContext(AuthContext)    │',
    '│                                             │',
    '│ Found 4 matches in 2 files                  │',
    '└──────────────────────────────────────────────┘',
    '',
    '┌─ GLOB: Find Files ───────────────────────────┐',
    '│ Pattern: "**/*.test.ts"                     │',
    '│                                             │',
    '│ src/auth/login.test.ts                      │',
    '│ src/hooks/useAuth.test.ts                   │',
    '│ src/components/Button.test.ts               │',
    '│ src/utils/validate.test.ts                  │',
    '│                                             │',
    '│ Found 4 files matching pattern              │',
    '└──────────────────────────────────────────────┘',
    '',
    'Grep: WHAT is inside files',
    'Glob: WHERE files are located',
  ],

  'task-tool': [
    '> Using Task tool (Subagent)...',
    '',
    '$ claude "analyze our auth implementation"',
    '',
    '> Spawning subagent: Explore',
    '',
    '┌─ Subagent Context ───────────────────────────┐',
    '│ Fresh 200K context window                   │',
    '│ Read: 23 files                              │',
    '│ Grep: 8 patterns                            │',
    '│ Analyzed: Authentication flow               │',
    '└──────────────────────────────────────────────┘',
    '',
    '> Subagent complete. Returning summary...',
    '',
    '┌─ Summary Returned ───────────────────────────┐',
    '│ Auth implementation analysis:               │',
    '│                                             │',
    '│ ● JWT tokens with 24h expiry                │',
    '│ ● Refresh token rotation enabled            │',
    '│ ● Sessions stored in Redis                  │',
    '│ ● Middleware at: src/middleware/auth.ts     │',
    '│                                             │',
    '│ Recommendations:                            │',
    '│ ● Add rate limiting to login endpoint       │',
    '│ ● Consider shorter JWT expiry (1h)          │',
    '└──────────────────────────────────────────────┘',
    '',
    'Your main context: Only summary added (~200 tokens)',
    'Subagent explored: 23 files (~15,000 tokens)',
  ],

  // ==========================================================================
  // CHAPTER 4: THE ART OF INCANTATION (Prompting)
  // ==========================================================================

  'think-first': [
    '> Plan Mode (Shift+Tab twice)',
    '',
    '$ [Plan Mode activated]',
    '',
    '┌─ Phase 1: Exploration ───────────────────────┐',
    '│ > Reading project structure...              │',
    '│ > Analyzing existing patterns...            │',
    '│ > Identifying dependencies...               │',
    '└──────────────────────────────────────────────┘',
    '',
    '┌─ Phase 2: Plan Document ─────────────────────┐',
    '│ ## Implementation Plan                      │',
    '│                                             │',
    '│ ### Approach                                │',
    '│ Add pagination to fetchData() using         │',
    '│ existing API limit/offset params            │',
    '│                                             │',
    '│ ### Files to Modify                         │',
    '│ 1. src/services/api.ts - Add params         │',
    '│ 2. src/hooks/useData.ts - Handle pages      │',
    '│ 3. src/components/List.tsx - Add controls   │',
    '│                                             │',
    '│ ### Risks                                   │',
    '│ - Breaking change for existing callers      │',
    '│   → Mitigation: Default values              │',
    '└──────────────────────────────────────────────┘',
    '',
    '> Waiting for your approval...',
    '> [Enter] to proceed, or provide feedback',
  ],

  'be-specific': [
    '> Prompt Specificity Comparison',
    '',
    '┌─ ✗ BAD: Vague Prompt ────────────────────────┐',
    '│ "Fix the login"                             │',
    '│                                             │',
    '│ > Claude response:                          │',
    '│   "Could you clarify what\'s wrong?          │',
    '│    - Not validating input?                  │',
    '│    - Error handling?                        │',
    '│    - Styling issues?                        │',
    '│    - API connection?"                       │',
    '│                                             │',
    '│ Wasted: ~500 tokens on clarification        │',
    '└──────────────────────────────────────────────┘',
    '',
    '┌─ ✓ GOOD: Specific Prompt ────────────────────┐',
    '│ "In src/auth/login.ts, LoginForm doesn\'t    │',
    '│  validate email format before submission.   │',
    '│  Add email regex validation in handleSubmit │',
    '│  and show error message below email input." │',
    '│                                             │',
    '│ > Claude response:                          │',
    '│   [Immediately reads file and makes edit]   │',
    '│                                             │',
    '│ Saved: Direct to implementation             │',
    '└──────────────────────────────────────────────┘',
    '',
    'Specificity checklist:',
    '☐ File path',
    '☐ Function/component name',
    '☐ Current behavior',
    '☐ Desired behavior',
    '☐ Where to make change',
  ],

  'tell-not-to': [
    '> The Power of Constraints',
    '',
    '┌─ Without Constraints ────────────────────────┐',
    '│ "Add email validation to login"             │',
    '│                                             │',
    '│ Claude does:                                │',
    '│ ✓ Adds email validation (requested)         │',
    '│ + Refactors surrounding code                │',
    '│ + Adds TypeScript types everywhere          │',
    '│ + Adds comprehensive error handling         │',
    '│ + Creates new validation utility file       │',
    '│ + Updates 3 other files for consistency     │',
    '│                                             │',
    '│ Scope: 1 task → 6 changes                   │',
    '└──────────────────────────────────────────────┘',
    '',
    '┌─ With Constraints ───────────────────────────┐',
    '│ "Add email validation to login.             │',
    '│  DON\'T refactor other code.                 │',
    '│  DON\'T add types to unchanged lines.        │',
    '│  DON\'T modify any other files."             │',
    '│                                             │',
    '│ Claude does:                                │',
    '│ ✓ Adds email validation only                │',
    '│                                             │',
    '│ Scope: 1 task → 1 change                    │',
    '└──────────────────────────────────────────────┘',
    '',
    'Add constraints to CLAUDE.md for recurring ones:',
    '"Never refactor code I didn\'t ask about"',
  ],

  'give-context': [
    '> Context Transforms Quality',
    '',
    '┌─ Without Context ────────────────────────────┐',
    '│ "Add pagination"                            │',
    '│                                             │',
    '│ Claude assumes:                             │',
    '│ - Generic pagination component              │',
    '│ - Arbitrary page sizes                      │',
    '│ - No understanding of your scale            │',
    '└──────────────────────────────────────────────┘',
    '',
    '┌─ With Context ───────────────────────────────┐',
    '│ "We\'re getting timeout errors in production │',
    '│  for users with large datasets (10K+ rows). │',
    '│  The fetchData function needs pagination.   │',
    '│  Our API already supports limit/offset.     │',
    '│  Keep backwards compatibility for existing  │',
    '│  callers that don\'t pass page params."      │',
    '│                                             │',
    '│ Claude understands:                         │',
    '│ ✓ Performance is the goal (not just UX)     │',
    '│ ✓ 10K+ rows = needs efficient pagination    │',
    '│ ✓ API already supports it (just frontend)   │',
    '│ ✓ Must not break existing code              │',
    '└──────────────────────────────────────────────┘',
    '',
    'Context types:',
    '• WHY: User complaint, perf issue, tech debt',
    '• CONSTRAINTS: Can\'t change API, deadline',
    '• WHO: Internal tool vs public API',
    '• WHAT FAILED: Previous attempts',
  ],

  'iterate': [
    '> Iterative Refinement',
    '',
    '┌─ Attempt 1 ──────────────────────────────────┐',
    '│ Claude\'s edit changes API signature         │',
    '│                                             │',
    '│ Your response:                              │',
    '│ "That changes the API signature - existing  │',
    '│  callers would break. Keep the original     │',
    '│  params, add pagination as optional new     │',
    '│  params with sensible defaults."            │',
    '└──────────────────────────────────────────────┘',
    '',
    '┌─ Attempt 2 ──────────────────────────────────┐',
    '│ Structure good, but error handling missing  │',
    '│                                             │',
    '│ Your response:                              │',
    '│ "Good structure. The error handling on      │',
    '│  line 45 should throw instead of returning  │',
    '│  null - we handle errors at the component   │',
    '│  level."                                    │',
    '└──────────────────────────────────────────────┘',
    '',
    '┌─ Attempt 3 ──────────────────────────────────┐',
    '│ ✓ Implementation correct                    │',
    '└──────────────────────────────────────────────┘',
    '',
    'Each iteration ADDS context.',
    'Failed attempts inform the next one.',
    'DON\'T /clear and start over - iterate!',
  ],

  // ==========================================================================
  // CHAPTER 5: THE WAND RACK (Skills)
  // ==========================================================================

  'what-are-skills': [
    '> Skills: Domain Knowledge for Claude',
    '',
    '┌─ What is a Skill? ───────────────────────────┐',
    '│ A markdown file that teaches Claude how to  │',
    '│ do something specific to YOUR work          │',
    '│                                             │',
    '│ ~/.claude/skills/commit/SKILL.md            │',
    '│ .claude/skills/api-design/SKILL.md          │',
    '└──────────────────────────────────────────────┘',
    '',
    '┌─ How They Work ──────────────────────────────┐',
    '│ 1. You create SKILL.md files                │',
    '│ 2. Claude loads skill descriptions at start │',
    '│ 3. When task matches, full skill loads      │',
    '│ 4. Claude follows skill instructions        │',
    '└──────────────────────────────────────────────┘',
    '',
    '> Example triggers:',
    '',
    '$ "help me write a commit message"',
    '  → commit-messages skill activates',
    '',
    '$ "create a new API endpoint"',
    '  → api-design skill activates',
    '',
    '$ "review this PR for security"',
    '  → security-review skill activates',
    '',
    'Skills live in:',
    '  ~/.claude/skills/     (personal)',
    '  .claude/skills/       (team, in git)',
  ],

  'skill-structure': [
    '> Skill File Structure',
    '',
    '$ cat ~/.claude/skills/commit/SKILL.md',
    '',
    '---',
    'name: commit-messages',
    'description: Generate commit messages following',
    '  our team\'s conventions. Use when creating',
    '  commits or helping with commit messages.',
    '---',
    '',
    '# Commit Message Format',
    '',
    'All commits follow conventional commits:',
    '- feat: New feature for users',
    '- fix: Bug fix for users',
    '- refactor: Code change (no behavior change)',
    '- docs: Documentation only',
    '- test: Adding or updating tests',
    '',
    '## Format',
    '',
    '`type(scope): imperative description`',
    '',
    '## Examples',
    '',
    'Good:',
    '  feat(auth): add password reset flow',
    '  fix(cart): prevent negative quantities',
    '',
    'Bad:',
    '  Fixed stuff',
    '  WIP',
    '  Update code',
    '',
    '───────────────────────────────────────────────',
    'CRITICAL: The description determines',
    'when Claude applies this skill!',
  ],

  'progressive-disclosure': [
    '> Progressive Disclosure',
    '',
    '┌─ At Startup ─────────────────────────────────┐',
    '│ Claude loads ONLY skill metadata:           │',
    '│                                             │',
    '│ ┌ commit-messages ─────────────────────┐    │',
    '│ │ desc: "Generate commits..." (~20 tok)│    │',
    '│ └──────────────────────────────────────┘    │',
    '│ ┌ api-design ──────────────────────────┐    │',
    '│ │ desc: "Design REST APIs..." (~25 tok)│    │',
    '│ └──────────────────────────────────────┘    │',
    '│ ┌ security-review ─────────────────────┐    │',
    '│ │ desc: "Review for vuln..." (~30 tok) │    │',
    '│ └──────────────────────────────────────┘    │',
    '│                                             │',
    '│ Total: ~75 tokens for 3 skills              │',
    '│ (Full content: ~3,000 tokens)               │',
    '└──────────────────────────────────────────────┘',
    '',
    '┌─ When Triggered ─────────────────────────────┐',
    '│ User: "help me write a commit"              │',
    '│                                             │',
    '│ > Skill matched: commit-messages            │',
    '│ > Loading full skill content...             │',
    '│ > +800 tokens added to context              │',
    '│                                             │',
    '│ Claude now has complete instructions        │',
    '└──────────────────────────────────────────────┘',
    '',
    'Result: 50 skills = ~1000 tokens at startup',
    '        Only triggered skills use full context',
  ],

  'skill-examples': [
    '> Real-World Skill Examples',
    '',
    '┌─ Database Queries ───────────────────────────┐',
    '│ name: db-patterns                           │',
    '│ desc: "Our PostgreSQL patterns..."          │',
    '│                                             │',
    '│ Content: Schema info, common joins,         │',
    '│ index hints, performance patterns           │',
    '└──────────────────────────────────────────────┘',
    '',
    '┌─ Code Review ────────────────────────────────┐',
    '│ name: review-checklist                      │',
    '│ desc: "Team code review standards..."       │',
    '│                                             │',
    '│ Content: Security checks, perf checks,      │',
    '│ style guide, test requirements              │',
    '└──────────────────────────────────────────────┘',
    '',
    '┌─ Meeting Notes ──────────────────────────────┐',
    '│ name: meeting-format                        │',
    '│ desc: "Structure meeting notes..."          │',
    '│                                             │',
    '│ Content: Template, attendee format,         │',
    '│ action item syntax, follow-up tags          │',
    '└──────────────────────────────────────────────┘',
    '',
    '┌─ API Design ─────────────────────────────────┐',
    '│ name: api-conventions                       │',
    '│ desc: "REST API design patterns..."         │',
    '│                                             │',
    '│ Content: URL patterns, error formats,       │',
    '│ auth headers, versioning scheme             │',
    '└──────────────────────────────────────────────┘',
    '',
    'Skills work for ANYTHING you explain repeatedly',
  ],

  'skill-triggers': [
    '> Skill Trigger Testing',
    '',
    '┌─ Test Different Phrasings ───────────────────┐',
    '│ $ "write a commit message"                  │',
    '│   → ✓ commit-messages skill triggered       │',
    '│                                             │',
    '│ $ "help me commit this"                     │',
    '│   → ✓ commit-messages skill triggered       │',
    '│                                             │',
    '│ $ "what should the commit say?"             │',
    '│   → ✗ Not triggered (too vague)             │',
    '│   → Fix: Add "commit message" to desc       │',
    '└──────────────────────────────────────────────┘',
    '',
    '┌─ Force Trigger ──────────────────────────────┐',
    '│ $ "utilize commit-messages skill"           │',
    '│   → Always triggers explicitly              │',
    '└──────────────────────────────────────────────┘',
    '',
    '┌─ Check Available Skills ─────────────────────┐',
    '│ $ "What skills do you have?"                │',
    '│                                             │',
    '│ > Available skills:                         │',
    '│   • commit-messages                         │',
    '│   • api-design                              │',
    '│   • security-review                         │',
    '│   • meeting-notes                           │',
    '└──────────────────────────────────────────────┘',
    '',
    'Description tips:',
    '- Include all trigger phrases',
    '- Be specific about WHEN to apply',
    '- Test with real prompts',
  ],

  // ==========================================================================
  // CHAPTER 6: THE SUMMONING SANCTUM (Subagents)
  // ==========================================================================

  'what-are-subagents': [
    '> Subagents: Fresh Context Windows',
    '',
    '┌─ Main Conversation ──────────────────────────┐',
    '│ Your 200K context window                    │',
    '│ Contains: All your messages + tool results  │',
    '│ Usage: ~45% (90K tokens)                    │',
    '│                                             │',
    '│ Problem: Reading 30 more files would        │',
    '│ push to dangerous 75%+ territory            │',
    '└──────────────────────────────────────────────┘',
    '',
    '               ↓ Spawn subagent',
    '',
    '┌─ Subagent Context ───────────────────────────┐',
    '│ FRESH 200K context window                   │',
    '│ Contains: Only the delegated task           │',
    '│ Usage: ~5% (starting fresh)                 │',
    '│                                             │',
    '│ Can: Read 30 files without affecting        │',
    '│ your main conversation                      │',
    '└──────────────────────────────────────────────┘',
    '',
    '               ↓ Returns summary',
    '',
    '┌─ Main Conversation ──────────────────────────┐',
    '│ Usage: ~46% (only summary added)            │',
    '│ Got: Distilled knowledge from 30 files      │',
    '│ Added: ~200 tokens (the summary)            │',
    '└──────────────────────────────────────────────┘',
  ],

  'builtin-spirits': [
    '> Built-in Subagent Types',
    '',
    '┌─ EXPLORE (Scout Spirit) ─────────────────────┐',
    '│ Purpose: Fast codebase exploration          │',
    '│ Tools: Read, Grep, Glob (read-only)         │',
    '│ Model: Claude Haiku (fast, cheap)           │',
    '│                                             │',
    '│ Use for:                                    │',
    '│ • "Where is X implemented?"                 │',
    '│ • "Find all uses of Y"                      │',
    '│ • "Map the auth flow"                       │',
    '└──────────────────────────────────────────────┘',
    '',
    '┌─ PLAN (Sage Spirit) ─────────────────────────┐',
    '│ Purpose: Research for planning              │',
    '│ Tools: Read, Grep, Glob (read-only)         │',
    '│ Model: Claude Opus (deep reasoning)         │',
    '│                                             │',
    '│ Use for:                                    │',
    '│ • Architectural decisions                   │',
    '│ • Understanding complex systems             │',
    '│ • Trade-off analysis                        │',
    '└──────────────────────────────────────────────┘',
    '',
    '┌─ GENERAL-PURPOSE (Battle Mage) ──────────────┐',
    '│ Purpose: Multi-step implementation          │',
    '│ Tools: All tools                            │',
    '│ Model: Claude Sonnet (balanced)             │',
    '│                                             │',
    '│ Use for:                                    │',
    '│ • "Implement this feature in isolation"     │',
    '│ • "Refactor this module"                    │',
    '│ • Complex multi-file changes                │',
    '└──────────────────────────────────────────────┘',
  ],

  'delegation-pattern': [
    '> Delegation & Return Pattern',
    '',
    '$ claude "research auth best practices',
    '          and implement password reset"',
    '',
    '> Main agent reasoning:',
    '  "This needs research + implementation.',
    '   I\'ll delegate research first."',
    '',
    '┌─ Delegation ─────────────────────────────────┐',
    '│ > Spawning: Explore subagent                │',
    '│ > Task: "Find auth patterns in codebase,    │',
    '│          identify password reset location"  │',
    '│                                             │',
    '│   [Subagent reads 15 files privately]       │',
    '│                                             │',
    '│ > Summary returned:                         │',
    '│   "Auth in src/auth/, password reset        │',
    '│    should go in src/auth/reset.ts           │',
    '│    Pattern: Express + JWT + nodemailer"     │',
    '└──────────────────────────────────────────────┘',
    '',
    '> Main agent continues:',
    '  "Now I understand the patterns.',
    '   Implementing password reset..."',
    '',
    '> Edit: src/auth/reset.ts',
    '> Edit: src/routes/auth.ts',
    '> Write: src/auth/reset.test.ts',
    '',
    '───────────────────────────────────────────────',
    'Subagent: Explored 15 files (~10K tokens)',
    'Main context: Received ~150 token summary',
  ],

  'context-isolation': [
    '> Context Isolation',
    '',
    '┌─ Main Context ───────────────────────────────┐',
    '│                                             │',
    '│  Your conversation                          │',
    '│  ┌─────────────────────────────────────┐    │',
    '│  │ Messages, tool results, decisions   │    │',
    '│  │ Current: 85K tokens                 │    │',
    '│  └─────────────────────────────────────┘    │',
    '│                                             │',
    '│  Subagent summaries only:                   │',
    '│  ┌─────────────────────────────────────┐    │',
    '│  │ "Auth uses JWT, files in src/auth"  │    │',
    '│  │ Added: 150 tokens                   │    │',
    '│  └─────────────────────────────────────┘    │',
    '│                                             │',
    '└──────────────────────────────────────────────┘',
    '',
    '┌─ Subagent Context (Disposed) ────────────────┐',
    '│                                             │',
    '│  ┌─────────────────────────────────────┐    │',
    '│  │ Read: auth/login.ts (200 lines)     │    │',
    '│  │ Read: auth/session.ts (150 lines)   │    │',
    '│  │ Read: auth/jwt.ts (180 lines)       │    │',
    '│  │ Read: middleware/auth.ts (100 lines)│    │',
    '│  │ ... 11 more files ...               │    │',
    '│  │ Total: ~15,000 tokens               │    │',
    '│  └─────────────────────────────────────┘    │',
    '│                                             │',
    '│  [Context discarded after summary]          │',
    '│                                             │',
    '└──────────────────────────────────────────────┘',
    '',
    'You get the knowledge without the weight.',
  ],

  'custom-familiars': [
    '> Creating Custom Subagents',
    '',
    '$ cat .claude/agents/security-reviewer.md',
    '',
    '---',
    'name: security-reviewer',
    'description: Reviews code for security',
    '  vulnerabilities and OWASP top 10 issues.',
    'tools: Read, Grep, Glob',
    '---',
    '',
    'You are a security-focused code reviewer.',
    '',
    'When analyzing code, check for:',
    '1. Authentication/authorization gaps',
    '2. Injection vulnerabilities (SQL, XSS)',
    '3. Data exposure risks',
    '4. Insecure dependencies',
    '5. Hardcoded secrets',
    '',
    'Output format:',
    '- CRITICAL: Immediate action required',
    '- HIGH: Should fix before merge',
    '- MEDIUM: Consider fixing',
    '- LOW: Nice to have',
    '',
    '───────────────────────────────────────────────',
    'Locations:',
    '  ~/.claude/agents/    (personal)',
    '  .claude/agents/      (team, in git)',
    '',
    '$ /agents             # List available agents',
  ],

  'subagent-patterns': [
    '> Subagent Patterns',
    '',
    '┌─ Pattern 1: Research Before Action ──────────┐',
    '│ 1. Spawn Explore to understand codebase     │',
    '│ 2. Receive summary of findings              │',
    '│ 3. Make informed edits in main context      │',
    '└──────────────────────────────────────────────┘',
    '',
    '┌─ Pattern 2: Parallel Review Pipeline ────────┐',
    '│ Spawn multiple reviewers simultaneously:    │',
    '│                                             │',
    '│ ┌───────────┐  ┌───────────┐  ┌───────────┐ │',
    '│ │ Security  │  │ Style     │  │ Test Cov  │ │',
    '│ │ Reviewer  │  │ Checker   │  │ Analyzer  │ │',
    '│ └─────┬─────┘  └─────┬─────┘  └─────┬─────┘ │',
    '│       └──────────────┼──────────────┘       │',
    '│                      ↓                      │',
    '│              Main synthesizes               │',
    '└──────────────────────────────────────────────┘',
    '',
    '┌─ Pattern 3: Scoped Implementation ───────────┐',
    '│ Main: "Refactor auth" (too big)             │',
    '│ → Subagent 1: "Refactor login.ts"           │',
    '│ → Subagent 2: "Refactor session.ts"         │',
    '│ → Subagent 3: "Update tests"                │',
    '│ Each returns: "Done, changed X lines"       │',
    '└──────────────────────────────────────────────┘',
  ],

  // ==========================================================================
  // CHAPTER 7: THE PORTAL NEXUS (MCP)
  // ==========================================================================

  'what-is-mcp': [
    '> MCP: Model Context Protocol',
    '',
    '┌─ What It Does ───────────────────────────────┐',
    '│ Connects Claude to external services:       │',
    '│                                             │',
    '│   Claude  ←→  MCP Server  ←→  Service       │',
    '│                                             │',
    '│ Examples:                                   │',
    '│   Claude  ←→  github MCP  ←→  GitHub API    │',
    '│   Claude  ←→  slack MCP   ←→  Slack API     │',
    '│   Claude  ←→  postgres    ←→  Database      │',
    '└──────────────────────────────────────────────┘',
    '',
    '┌─ Why It Matters ─────────────────────────────┐',
    '│ WITHOUT MCP:                                │',
    '│   1. Ask Claude what to do                  │',
    '│   2. Switch to GitHub, create issue         │',
    '│   3. Switch to Slack, post update           │',
    '│   4. Switch back to Claude...               │',
    '│                                             │',
    '│ WITH MCP:                                   │',
    '│   1. "Create GitHub issue and post to Slack"│',
    '│   2. Done. No context switching.            │',
    '└──────────────────────────────────────────────┘',
    '',
    '> MCP eliminates context switching',
    '> Work stays in flow state',
  ],

  'connecting-services': [
    '> Adding MCP Connections',
    '',
    '┌─ Via CLI ────────────────────────────────────┐',
    '│ # Basic HTTP connection                     │',
    '│ $ claude mcp add github                     │',
    '│ > Connecting to github MCP server...        │',
    '│ > ✓ 12 tools now available                  │',
    '│                                             │',
    '│ # With authentication                       │',
    '│ $ claude mcp add github \\                   │',
    '│     --header "Authorization: Bearer $TOKEN" │',
    '└──────────────────────────────────────────────┘',
    '',
    '┌─ Via Settings ───────────────────────────────┐',
    '│ Settings → Connectors → GitHub              │',
    '│                                             │',
    '│ ┌──────────────────────────────────────┐    │',
    '│ │ GitHub MCP                           │    │',
    '│ │ ○ Not connected                      │    │',
    '│ │                                      │    │',
    '│ │ [Configure] [Connect]                │    │',
    '│ └──────────────────────────────────────┘    │',
    '└──────────────────────────────────────────────┘',
    '',
    '┌─ Check Current Connections ──────────────────┐',
    '│ $ /mcp                                      │',
    '│                                             │',
    '│ Connected servers:                          │',
    '│ ● github      12 tools                      │',
    '│ ● slack        6 tools                      │',
    '│ ● postgres     5 tools                      │',
    '└──────────────────────────────────────────────┘',
  ],

  'portal-examples': [
    '> MCP in Action',
    '',
    '┌─ GitHub Integration ─────────────────────────┐',
    '│ $ "Implement the feature in issue #142"     │',
    '│                                             │',
    '│ > MCP: github.get_issue(142)                │',
    '│ > Reading issue description...              │',
    '│ > Understanding requirements...             │',
    '│ > [implements feature]                      │',
    '│ > MCP: github.create_pr(branch, body)       │',
    '│ > ✓ PR #156 created                         │',
    '└──────────────────────────────────────────────┘',
    '',
    '┌─ Database Queries ───────────────────────────┐',
    '│ $ "Find users who signed up this week"      │',
    '│                                             │',
    '│ > MCP: postgres.query(                      │',
    '│     "SELECT * FROM users                    │',
    '│      WHERE created_at > NOW() - \'7 days\'"   │',
    '│   )                                         │',
    '│ > Found 847 users                           │',
    '└──────────────────────────────────────────────┘',
    '',
    '┌─ Slack Updates ──────────────────────────────┐',
    '│ $ "Post the deployment summary to #releases"│',
    '│                                             │',
    '│ > MCP: slack.post_message(                  │',
    '│     channel: "releases",                    │',
    '│     text: "v2.4.1 deployed..."              │',
    '│   )                                         │',
    '│ > ✓ Message posted                          │',
    '└──────────────────────────────────────────────┘',
  ],

  'chain-workflows': [
    '> Chained MCP Workflow',
    '',
    '$ "Check the latest Jira ticket, implement it,',
    '   and update the team in Slack"',
    '',
    '> Step 1: Jira MCP',
    '  Fetching latest assigned ticket...',
    '  JIRA-4521: "Add retry logic to payments"',
    '',
    '> Step 2: Codebase',
    '  Reading src/services/payments.ts...',
    '  Adding retry logic with exponential backoff...',
    '',
    '> Step 3: Testing',
    '  Running npm test...',
    '  ✓ All tests passing',
    '',
    '> Step 4: Git',
    '  Creating branch: feature/payment-retry',
    '  Committing changes...',
    '  Creating PR #203',
    '',
    '> Step 5: Jira MCP',
    '  Updating JIRA-4521 status: "In Review"',
    '  Adding PR link to ticket',
    '',
    '> Step 6: Slack MCP',
    '  Posting to #engineering:',
    '  "PR #203 ready for review - payment retry"',
    '',
    '───────────────────────────────────────────────',
    '6 services. 1 prompt. Zero context switching.',
  ],

  'mcp-safety': [
    '> MCP Security Considerations',
    '',
    '┌─ Official Connectors (Recommended) ──────────┐',
    '│ ● GitHub    - Official, verified            │',
    '│ ● Slack     - Official, verified            │',
    '│ ● Google    - Official, verified            │',
    '│ ● PostgreSQL - Standard, audited            │',
    '│ ● Linear    - Official, verified            │',
    '└──────────────────────────────────────────────┘',
    '',
    '┌─ Third-Party Connectors ─────────────────────┐',
    '│ ⚠ NOT verified by Anthropic                 │',
    '│                                             │',
    '│ Before using:                               │',
    '│ • Review source code on GitHub              │',
    '│ • Check what permissions requested          │',
    '│ • Prefer connectors from known vendors      │',
    '│ • Use minimal permissions possible          │',
    '└──────────────────────────────────────────────┘',
    '',
    '┌─ Security Commands ──────────────────────────┐',
    '│ $ /mcp                    # List connections │',
    '│ $ claude mcp remove NAME  # Disconnect      │',
    '│ $ claude mcp permissions  # View perms      │',
    '└──────────────────────────────────────────────┘',
    '',
    'Rule: Would you give this service your API key?',
    'If no → don\'t connect it to MCP',
  ],

  'compound-effect': [
    '> The Compound Effect',
    '',
    '┌─ Skills ─────────────────────────────────────┐',
    '│ Encode your patterns and conventions        │',
    '│ → Claude knows HOW to do things your way    │',
    '└─────────────────────┬────────────────────────┘',
    '                      │',
    '┌─ Subagents ─────────┼────────────────────────┐',
    '│ Delegate without    │ context pollution      │',
    '│ → Complex tasks stay manageable             │',
    '└─────────────────────┼────────────────────────┘',
    '                      │',
    '┌─ MCP ───────────────┼────────────────────────┐',
    '│ Connect external    │ services               │',
    '│ → No context switching, flow state          │',
    '└─────────────────────┼────────────────────────┘',
    '                      ↓',
    '',
    '┌─ Together ───────────────────────────────────┐',
    '│ "Implement JIRA-4521 following our API      │',
    '│  patterns, have security review it, then    │',
    '│  post update to Slack"                      │',
    '│                                             │',
    '│ • api-patterns skill → knows conventions    │',
    '│ • security-reviewer agent → isolated review │',
    '│ • jira/slack MCP → seamless integration     │',
    '│                                             │',
    '│ One prompt. Minutes of work. Quality output.│',
    '└──────────────────────────────────────────────┘',
  ],

  // ==========================================================================
  // CHAPTER 8: BREAKING THE LOOP (Troubleshooting)
  // ==========================================================================

  'breaking-loops': [
    '> Breaking Stuck Loops',
    '',
    '┌─ Signs of a Loop ────────────────────────────┐',
    '│ ✗ Same error 3+ times                       │',
    '│ ✗ "Let me try that again..."                │',
    '│ ✗ Repeating similar approaches              │',
    '│ ✗ Claude apologizing repeatedly             │',
    '└──────────────────────────────────────────────┘',
    '',
    '┌─ DON\'T Do This ──────────────────────────────┐',
    '│ ✗ Explain more (if 3 explanations failed,   │',
    '│   the 4th won\'t help)                       │',
    '│ ✗ Just repeat the same request              │',
    '│ ✗ Add more words to the prompt              │',
    '└──────────────────────────────────────────────┘',
    '',
    '┌─ DO This ────────────────────────────────────┐',
    '│ $ /clear                                    │',
    '│ > Context cleared. Fresh start.             │',
    '│                                             │',
    '│ Then try:                                   │',
    '│ • Simpler version of the task               │',
    '│ • Different framing entirely                │',
    '│ • Minimal working example                   │',
    '│ • Break into smaller steps                  │',
    '└──────────────────────────────────────────────┘',
    '',
    'If Claude struggles, the task decomposition',
    'is wrong - not the explanation quality.',
  ],

  'reframing': [
    '> Three Reframing Strategies',
    '',
    '┌─ 1. Change Abstraction Level ────────────────┐',
    '│ Too high-level:                             │',
    '│   "Fix the authentication"                  │',
    '│                                             │',
    '│ More specific:                              │',
    '│   "In src/auth/login.ts line 45, the        │',
    '│    validateToken function returns null      │',
    '│    instead of throwing on invalid tokens"   │',
    '│                                             │',
    '│ Or zoom out:                                │',
    '│   "I need users to stay logged in longer"   │',
    '└──────────────────────────────────────────────┘',
    '',
    '┌─ 2. Change Starting Point ───────────────────┐',
    '│ Instead of:                                 │',
    '│   "Modify this function to add caching"     │',
    '│                                             │',
    '│ Try:                                        │',
    '│   "Here\'s what the function should do:      │',
    '│    [full specification]. Rewrite it."       │',
    '└──────────────────────────────────────────────┘',
    '',
    '┌─ 3. Relax Constraints Temporarily ───────────┐',
    '│ If stuck on:                                │',
    '│   "Add feature X without changing the API"  │',
    '│                                             │',
    '│ Try:                                        │',
    '│   "How would you add X if you COULD change  │',
    '│    the API? What\'s the ideal approach?"     │',
    '│                                             │',
    '│ Then: Work backwards to constraints         │',
    '└──────────────────────────────────────────────┘',
  ],

  'input-quality': [
    '> The Input Quality Mirror',
    '',
    '┌─ Vague Input → Vague Output ─────────────────┐',
    '│ "Make it better"                            │',
    '│                                             │',
    '│ Claude: "Could you specify what aspect      │',
    '│ you\'d like improved? Performance? UX?       │',
    '│ Readability? Error handling? Testing?"      │',
    '└──────────────────────────────────────────────┘',
    '',
    '┌─ Contradictory → Confused ───────────────────┐',
    '│ "Add comprehensive error handling but       │',
    '│  keep the function under 10 lines"          │',
    '│                                             │',
    '│ Claude: [tries both, achieves neither]      │',
    '└──────────────────────────────────────────────┘',
    '',
    '┌─ Missing Context → Hallucinated ─────────────┐',
    '│ "Update the payment flow"                   │',
    '│                                             │',
    '│ Claude: [invents a payment flow that        │',
    '│  doesn\'t match your actual system]          │',
    '└──────────────────────────────────────────────┘',
    '',
    '┌─ Quality Checklist ──────────────────────────┐',
    '│ ☐ Is my prompt specific enough?             │',
    '│ ☐ Did I provide necessary context?          │',
    '│ ☐ Are my constraints compatible?            │',
    '│ ☐ Have I tried showing vs telling?          │',
    '└──────────────────────────────────────────────┘',
  ],

  'escape-hatches': [
    '> Emergency Controls',
    '',
    '┌─ Interrupt Operations ───────────────────────┐',
    '│ [Escape]        Stop current operation      │',
    '│ [Escape][Esc]   Exit Claude Code entirely   │',
    '└──────────────────────────────────────────────┘',
    '',
    '┌─ Undo Changes ───────────────────────────────┐',
    '│ $ /undo                                     │',
    '│ > Reverted: src/auth/login.ts               │',
    '│ > Reverted: src/hooks/useAuth.ts            │',
    '│ > 2 files restored                          │',
    '└──────────────────────────────────────────────┘',
    '',
    '┌─ Git Safety Net ─────────────────────────────┐',
    '│ Before risky experiments:                   │',
    '│ $ git stash                                 │',
    '│                                             │',
    '│ If things go wrong:                         │',
    '│ $ git stash pop       # Restore             │',
    '│ $ git checkout .      # Nuclear option      │',
    '└──────────────────────────────────────────────┘',
    '',
    '┌─ Fresh Context ──────────────────────────────┐',
    '│ $ /clear                                    │',
    '│ > Conversation cleared                      │',
    '│ > CLAUDE.md still loaded                    │',
    '│ > Ready for fresh start                     │',
    '└──────────────────────────────────────────────┘',
    '',
    'You always have control.',
    'Escape → Undo → Git → /clear',
  ],

  'conclusion': [
    '> Your Claude Code Mastery',
    '',
    '┌─ The Foundations ────────────────────────────┐',
    '│ ● Agentic Loop    - Prompt → Act → Repeat   │',
    '│ ● Context Window  - 200K tokens, use wisely │',
    '│ ● CLAUDE.md       - Your persistent memory  │',
    '└──────────────────────────────────────────────┘',
    '',
    '┌─ The Tools ──────────────────────────────────┐',
    '│ ● Read/Edit/Write - File operations         │',
    '│ ● Bash            - Shell commands          │',
    '│ ● Grep/Glob       - Search & find           │',
    '│ ● Task/Todo       - Subagents & tracking    │',
    '└──────────────────────────────────────────────┘',
    '',
    '┌─ The Multipliers ────────────────────────────┐',
    '│ ● Skills          - Domain knowledge        │',
    '│ ● Subagents       - Context isolation       │',
    '│ ● MCP             - External connections    │',
    '└──────────────────────────────────────────────┘',
    '',
    '┌─ The Commands ───────────────────────────────┐',
    '│ /clear   - Fresh context                    │',
    '│ /compact - Compress context                 │',
    '│ /model   - Switch models                    │',
    '│ /undo    - Revert changes                   │',
    '│ /mcp     - View connections                 │',
    '│ /agents  - List subagents                   │',
    '└──────────────────────────────────────────────┘',
    '',
    'The magic is yours to wield. Go create.',
  ],
}

/**
 * Get beat-specific terminal content, or return undefined to fall back to mode-based content.
 */
export function getBeatTerminalContent(beatId: string): string[] | undefined {
  return BEAT_TERMINAL_CONTENT[beatId]
}
